### ISSUE TITLE
Gutter not showing diffs

### ISSUE THREAD

**Issue by haasDev** [atom/git-diff#80] opened 2015-12-02 21:37 UTC
My gutter is not showing the "diffs" in the gutter.  I have just recently started using atom and noticed the package comes preinstalled but I have never had this feature show up in any of my git projects.

**Comment by 50Wliu** [comment] 2015-12-02 21:47
Closing as a duplicate of #75, please subscribe there for updates.

**Closed by 50Wliu** 2015-12-02 21:47 UTC
