### ISSUE TITLE
No highlighting when git is not the home project

### ISSUE THREAD

**Issue by muuvmuuv** [atom/git-diff#151] opened 2018-05-17 09:28 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When I have a git project (no supp module) inside my atom project (no git) I don't get any highlightings and I think it does not recognise the folder as a git project. I found some similiar topics, but that does not seem to fix my problem. I really want to use it that way.

Related answers:
- https://discuss.atom.io/t/atom-not-recognizing-git-repository/20130
- https://discuss.atom.io/t/git-diff-does-not-seem-to-be-working-at-all/5609/14

### Steps to Reproduce

1. Create a project and put a git project inside a deeper structure
2. Change something in the git project

**Expected behavior:** Shows diffs as in a normal git project when it is the root

**Actual behavior:** Does nothing

**Reproduces how often:** 100%

### Versions

Atom:
```
Atom    : 1.27.0
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0
```

APM:
```
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.27.0
python 2.7.15
git 2.15.1

```

### Additional Information

Image of the structure: https://imgur.com/mLU7q0d

**Comment by rsese** [comment] 2018-05-17 19:28
Thanks for contributing!

We noticed that this is a duplicate of https://github.com/atom/git-diff/issues/55 (and as mentioned there, the larger issue is https://github.com/atom/atom/issues/2203) so you can subscribe there for updates if you'd like.

> . I found some similiar topics, but that does not seem to fix my problem.

There's no fix or workaround for this behavior at the moment other than opening a Git project directly as the root of the project rather than opening a higher level directory.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-05-17 19:28 UTC
