### ISSUE TITLE
Doesn't showing diff for the git repo inside a folder

### ISSUE THREAD

**Issue by ULTIMATEUPGRADE** [atom/git-diff#83] opened 2016-01-07 05:52 UTC
For example 
I am having a folder named the "Main"
Inside that folder I have 2 git repositories 
     Named "test 1" and "test 2"
if I added the "Main" Folder as a project folder in atom
     Then the git diff is not showing for my both repositories

**Comment by mnquintana** [comment] 2016-01-07 16:57
Thanks for the suggestion! This looks like a duplicate of https://github.com/atom/git-diff/issues/47 – feel free to subscribe there for updates.

**Closed by mnquintana** 2016-01-07 16:57 UTC
