### ISSUE TITLE
Files under a folder with accents on the name are not detected as committed

### ISSUE THREAD

**Issue by jmfederico** [atom/git-diff#115] opened 2016-11-02 01:35 UTC
I am using atom 1.11.2 with git-diff 1.1.0 on OSX Sierra.

I have a repo which has a folder with an accented character (Bogotá), files under that folder are always shown as new (uncommitted) even though the file is definitely committed.

## As shown in Atom
<img width="193" alt="screen_shot_2016-11-01_at_20_32_05" src="https://cloud.githubusercontent.com/assets/237977/19913652/a31cd420-a072-11e6-82c6-a8e4a374945b.png">

## Current repo status
<img width="568" alt="screen shot 2016-11-01 at 20 35 45" src="https://cloud.githubusercontent.com/assets/237977/19913673/cfc27926-a072-11e6-9f8d-7fa8b35e9ea5.png">

**Comment by 50Wliu** [comment] 2016-11-02 01:54
This is a duplicate of atom/atom#1890 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-11-02 01:54 UTC
