### ISSUE TITLE
Unmodified lines showing as modified

### ISSUE THREAD

**Issue by sheck** [atom/git-diff#65] opened 2015-06-29 22:51 UTC
Every line in all of my files are showing as modified. The tree view does not mark them as modified and git status comes back clean. The status bar also does not show any changes. I believe I have my git line endings are set up properly. I've followed the solutions on a bunch of related issues — but no luck.

I'm using Parallels on my Mac (OSX Yosemite) to access the Windows partition. Running git status from OSX and Windows both comes back clean.

Anything else I should look into?

**Comment by capi** [comment] 2015-07-01 21:43
I can see this issue runing Atom under Windows 7 as well. If i have `core.autocrlf` to `true`, it will show all files as modified all the time. If I set it to `false` or `input`, some files will work properly, some won't, some won't even show as modified, even if the have modification markers inside the file.

**Comment by lee-dohm** [comment] 2015-07-02 05:07
My assumption is that because you are running Windows that you're having a line-ending issue. I suspect this is a duplicate of atom/atom#3768 and can be resolved in the same way.

The advice here might help too: https://discuss.atom.io/t/atom-on-windows-incorrectly-showing-files-as-modified-git/12805

Please let us know if this is not the case.

**Comment by capi** [comment] 2015-07-02 18:13
First of all, I must say that I am using the [Cygwin](https://cygwin.com/) version git on Windows, using it directly from a Cygwin terminal.

And I think I just figured out the cause of the issue, and I'm not sure if there is anything to be done about it.

I have the following settings in `.git/config`:

    [core]
    repositoryformatversion = 0
    filemode = false
    bare = false
    logallrefupdates = true
    ignorecase = true

and `core.autocrlf` is `true` via  _global_ git setting. And this seems to be the cause for the trouble, if I add it additionally as a local setting for the repository, it seems to work.

Of course Atom on Windows won't be aware of my Cygwin's `/home/martin/.gitconfig`, so it won't see the global settings.

**Comment by lee-dohm** [comment] 2015-07-03 00:37
Ok, so it would appear that your configuration was incorrect rather than there being a bug in Atom. I'm glad it got fixed :grinning:

**Closed by lee-dohm** 2015-07-03 00:37 UTC
Labels: invalid, windows

**Comment by capi** [comment] 2015-07-03 07:23
@lee-dohm Hmm, "incorrect" is debatable from my point of view. I think there should be a way to tell ` git-diff` about the global settings file. I would consider global settings to be part of the repositories configuration. It just seems to be hard to decide what the global configuration is on Windows when using Cygwin.

**Comment by mr-bat** [comment] 2017-10-22 12:29
I'm having this issue on mac.

**Comment by lee-dohm** [comment] 2017-10-23 20:55
@mr-bat If you're running into something that you consider to be a bug, please open a new issue and fill out the template.
