### ISSUE TITLE
[bug?] git-diff shows nothing when project root is not a git repo.

### ISSUE THREAD

**Issue by trusktr** [atom/git-diff#103] opened 2016-06-21 02:37 UTC
I have a project where the root contains two git repositories, but the root of the project is not itself a git repo:

```
project
  repo1
  repo2
```

When I edit files in either of repo1 or repo2, the editor does not show any changes in those files.

Seems like git-diff only works when the project root is a git repo, otherwise it does nothing.

I have various projects like this, where the root is not a repo, so the package unfortunately does nothing in those cases.

**Comment by 50Wliu** [comment] 2016-06-21 15:08
This is a duplicate of atom/atom#2203 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-06-21 15:08 UTC
