### ISSUE TITLE
Editor gutter lines not displaying in Atom 1.0.19

### ISSUE THREAD

**Issue by jcderose** [atom/git-diff#75] opened 2015-10-16 16:31 UTC
I recently upgraded to Atom 1.0.19 (with git-diff 0.56.0) and the editor gutter lines have disappeared. The colored folders (highlighting changes to files/folders) has also disappeared. I tried disabling/re-enabling the git-diff package but that did not resolve the issue. I also tried un-installing/re-installing Atom but that did not resolve the issue either.

**Comment by mikewink** [comment] 2015-10-24 20:57
I have currently the same problem as stated by jcderose with the same setup. I'm running minimap-git-diff and it works and git-diff works too when icons are enabled.

**Comment by Dayjo** [comment] 2015-10-27 12:37
I also have no markers / icons on the gutter since Atom 1.0.19. Anyone need any specific info?

**Comment by ilikebits** [comment] 2015-10-28 20:46
+1, seeing the same issue here, but icons don't even work for me. The gutter expands as if to make room for the icons, but nothing ever shows up.

**Comment by jcderose** [comment] 2015-10-28 20:48
@lee-dohm do you need any specific info from us to try reproducing the issue?

**Comment by murm** [comment] 2015-10-28 21:12
I have the same issue as well, also atom version 1.0.19 with 0.56.0 of git-diff

**Comment by 50Wliu** [comment] 2015-10-28 22:09
Can everyone please try to reproduce this in safe mode (`atom --safe`)?  Thanks.

**Comment by ilikebits** [comment] 2015-10-28 22:46
This issue still occurs for me in safe mode.

On 28 October 2015 at 15:09, Wliu <notifications@github.com> wrote:

> Can everyone please try to reproduce this in safe mode (atom --safe)?
> Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/atom/git-diff/issues/75#issuecomment-152013129>.
>



-- 
Leo Zhang
Berkeley EECS 2016
Previously Mithril, Kloudless, Feeding Forward, Captify

**Comment by jcderose** [comment] 2015-10-28 22:56
@50Wliu The issue still persists for me in safe mode.

**Comment by Dayjo** [comment] 2015-10-29 08:20
Still have the issue in safe mode. I'm on: `OS X El Capitan 10.11.1 (15B42)`

**Comment by izuzak** [comment] 2015-10-29 08:28
Do any of you have any styles defined in your styles.less file? Can you share a GIF which clearly demonstrates the problem, just so we're sure were all thinking about the same thing?

**Comment by jcderose** [comment] 2015-10-29 15:25
@izuzak here's my `styles.less` file: 

```
/*
 * Your Stylesheet
 *
 * This stylesheet is loaded when Atom starts up and is reloaded automatically
 * when it is changed and saved.
 *
 * Add your own CSS or Less to fully customize Atom.
 * If you are unfamiliar with Less, you can read more about it here:
 * http://lesscss.org
 */


/*
 * Examples
 * (To see them, uncomment and save)
 */

// style the background color of the tree view
.tree-view {
  // background-color: whitesmoke;
}

// style the background and foreground colors on the atom-text-editor-element itself
atom-text-editor {
  // color: white;
  // background-color: hsl(180, 24%, 12%);
}

// To style other content in the text editor's shadow DOM, use the ::shadow expression
atom-text-editor::shadow .cursor {
  // border-color: red;
}
```

I wasn't able to upload a screenshot, I'll try to get that added today.

**Comment by izuzak** [comment] 2015-10-29 15:30
Thanks, @jcderose -- I don't see anything strange there.

> I wasn't able to upload a screenshot, I'll try to get that added today.

A GIF would be more helpful, you can use this tool: http://www.cockos.com/licecap/

Also, can you share your config.cson file as well?

**Comment by jcderose** [comment] 2015-10-29 15:37
I just restarted Atom and it had removed my project folder - don't know why. I re-added my project folder and the gutter editor lines showed up (plus the file/folder highlights for edited files). I didn't do anything different so I'm not sure how this issue fixed itself? 

Here's my config.cson file if that helps any:
```
"*":
  "exception-reporting":
    userId: "21927fc7-5abe-14cb-8a31-ccc6471854a6"
  welcome:
    showOnStartup: false
  core: {}
  editor:
    invisibles: {}
  "git-diff":
    showIconsInEditorGutter: true
```

**Comment by Dayjo** [comment] 2015-10-30 11:00
Nothing in the gutter here;

![](http://c.dayjo.me/image/3V37471m1l1S/Screen%20Recording%202015-10-30%20at%2010.57%20a.m..gif)

My stylesheet is empty. My config;
![](http://c.dayjo.me/image/2D1R2J1v0K17/Image%202015-10-30%20at%2011.00.08%20a.m..png)

**Comment by izuzak** [comment] 2015-11-08 21:23
@Dayjo can you reproduce the problem in Atom 1.1.0? If so, can you confirm that you are making edits to files within a Git project and that the root of the project added as a root project folder in Atom? Can you share a GIF which shows that the tree view is correctly updating the color of edited files, and also that your are running Atom in safe mode? Also, have you tried temporarily moving the `~/.atom` folder to a different location (quit Atom, move the folder, then start Atom again)? That will make Atom forget all local data, so I'm wondering if that helps.

**Comment by Dayjo** [comment] 2015-11-12 11:34
Hi @izuzak,

So it turns out that I got it working on local repositories (git repos on my local machine). But I mostly work on repositories mounted via ssh (works in the same way really), and these repositories don't seem to work with the plugin.

**Comment by marcellodesales** [comment] 2015-11-28 20:43
Same here... Multiple projects... And I could never seen this plugin working...

![screen shot 2015-11-28 at 12 41 04 pm](https://cloud.githubusercontent.com/assets/131457/11453783/99dc7e66-95cd-11e5-899f-19acd5525cd7.png)

**Comment by gitlovenotwar** [comment] 2015-12-19 04:40
Same here! No icons +- showing.

**Comment by dpo** [comment] 2016-01-08 22:40
Same here. Atom 1.3.3.

**Comment by filipgorczynski** [comment] 2016-01-22 11:49
I am using Atom 1.2.4 @ Ubuntu Linux and found that diffs (markers) are not displayed in gutter and tree-view is not coloring files because of not selecting project directory. By this I mean directory in the tree-view should be directory that contains .git. Of course at the same time there may be many project directories but they shouldn't be under common parent directory.

**Comment by laander** [comment] 2016-01-27 18:59
Atom 1.4, disabling/enabling the plugin and restarting Atom fixed it for me. Yay!

**Comment by lee-dohm** [comment] 2016-01-27 19:11
It sounds like this is fixed for everyone (other than the `.git` directory not being at the root, for which we have a separate Issue https://github.com/atom/atom/issues/2203). Please let us know if this is *not* working for anyone!

**Comment by marcellodesales** [comment] 2016-01-28 07:00
Same here... Worked after upgrading, disabling/enabling it again!

<img width="235" alt="screen shot 2016-01-27 at 10 58 51 pm" src="https://cloud.githubusercontent.com/assets/131457/12637395/bdc576b0-c549-11e5-96c2-c4077e891a7a.png">

**Comment by lee-dohm** [comment] 2016-01-28 17:59
You're welcome. Glad it is working for you now :grinning:

**Comment by larslevie** [comment] 2016-02-05 15:49
Just ran into this after upgrading to Atom 1.4.3. I'm using minimap-git-diff, and I had to enable and disable both git-diff and minimap-git-diff and then restart in order to get things back to normal.

**Comment by lee-dohm** [comment] 2016-02-05 19:38
Thanks everyone for the responses. I'm going to close this since it seems it is fixed :grinning: Let us know if that changes!

**Closed by lee-dohm** 2016-02-05 19:38 UTC
Labels: bug, more-information-needed

**Comment by Alexspayne** [comment] 2016-04-03 16:06
I'm having this same problem with the gutter not showing anything on Atom 1.6.2
I've tried disabling/enabling the plugin and restarting atom.
My style sheet is empty. I tried removing and adding the project folder too.
I can see the git integration is working:
![image](https://cloud.githubusercontent.com/assets/8633216/14233351/ecc73ba0-f993-11e5-8c0c-70e33a322e1b.png)

But no changes are marked when I update the page
![gitdiff](https://cloud.githubusercontent.com/assets/8633216/14233360/395949ae-f994-11e5-9a3a-72eb6a5a8298.gif)

**Comment by lee-dohm** [comment] 2016-04-04 16:31
@Alexspayne please open a new Issue and include as much information as possible, including Atom version, OS version, are you accessing the repo on a remote file system, and can you replicate the problem in Safe Mode?

**Comment by renarsvilnis** [comment] 2016-05-12 21:06
@Alexspayne did you manage to solve the issue?
Migrating from Sublime to Atom, and this seems to be the only thing I can't get working.
On the lower right corner the same as @Alexspayne seem to have Atom recognize the repo.

<img width="307" alt="screen shot 2016-05-12 at 23 49 28" src="https://cloud.githubusercontent.com/assets/3515099/15230212/35630330-189d-11e6-9f07-626e76844aa5.png">

<img width="969" alt="screen shot 2016-05-12 at 23 58 42" src="https://cloud.githubusercontent.com/assets/3515099/15230268/7d8a0c62-189d-11e6-8de1-115c9ccf6c6a.png">


**My setup:**
Atom - v1.7.3 (*installed trough brew-casks and updated through app*)
OS  - OSX 10.11.4
Accessing the repo from local file system (*~/Downloads/project-name*)
UI Theme - One Dark
Syntax Theme - One Dark

**Have tried:**
disabling all Community packages
enabling/disabling git-diff
unisntalling/installing git-diff (`apm uninstall git-diff && apm install git-diff`)
tried running Atom in safe mode (`atom --safe`)

But without any luck.

Tried viewing the DOM of the gutter panel, doesn't seem to have anything, related to git-diff.

<img width="1088" alt="screen shot 2016-05-13 at 00 00 46" src="https://cloud.githubusercontent.com/assets/3515099/15230335/cd5ec412-189d-11e6-811e-ddc8145b99b9.png">

Does Atom show errors while executing packages? If so where? Developer Tools?

**Comment by mislam** [comment] 2016-10-15 15:58
I'm using Atom 1.11.1. I used to see the git-diff colors in the gutter before, but not any more. Why atom admin keeps closing this issue. This needs to be fixed.

**Comment by Ben3eeE** [comment] 2016-10-16 18:35
@mislam please open a new Issue and include as much information as possible, including Atom version, OS version, are you accessing the repo on a remote file system, and can you replicate the problem in Safe Mode?
