### ISSUE TITLE
doesn't work with gitdir: <path>

### ISSUE THREAD

**Issue by skybrian** [atom/git-diff#72] opened 2015-08-28 01:08 UTC
For reasons too annoying to explain, instead of the normal .git directory, I need to use a .git file with a gitdir: entry, as described at [1]. The git-diff plugin doesn't seem to display anything in this case.

[1] http://git-scm.com/docs/gitrepository-layout

**Comment by phord** [comment] 2015-09-18 14:02
It's not the same as #55.  It has the same effect, but it has a different root cause.  Atom doesn't recognize gitfiles (regular files named .git with 'gitdir: ' paths) as described in the link @skybrian gave.  But I think this is an atom bug, not a git-diff bug.

**Comment by maxbrunsfeld** [comment] 2018-09-06 23:07
Closing this in favor of https://github.com/atom/atom/issues/8168 since we're moving this package into the main Atom repository.

**Closed by maxbrunsfeld** 2018-09-06 23:07 UTC
Labels: enhancement
