### ISSUE TITLE
Uncaught Error: Couldn't convert text to a String

### ISSUE THREAD

**Issue by Manish-rai21bit** [atom/git-diff#138] opened 2017-08-13 06:14 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.10.5
**Thrown From**: [git-diff](https://github.com/atom/git-diff) package 1.3.6

### Stack Trace

Uncaught Error: Couldn't convert text to a String

```
At /Users/manishrai/Downloads/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:532

Error: Couldn't convert text to a String
    at TextBuffer.module.exports.TextBuffer.getText (/Users/manishrai/Downloads/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:532:94)
    at TextEditor.module.exports.TextEditor.getText (/Users/manishrai/Downloads/Atom.app/Contents/Resources/app/src/text-editor.js:1030:32)
    at GitDiffView.module.exports.GitDiffView.updateDiffs (/Users/manishrai/Downloads/Atom.app/Contents/Resources/app/node_modules/git-diff/lib/git-diff-view.js:162:103)
    at Immediate.<anonymous> (/Users/manishrai/Downloads/Atom.app/Contents/Resources/app/node_modules/git-diff/lib/git-diff-view.js:3:65)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
```

### Commands

```
```

### Non-Core Packages

```
atom-runner 2.7.1 
```

**Comment by rsese** [comment] 2017-08-14 21:26
Thanks for the report!  Can you confirm a few things for us?

* what were you doing at the time of the error?
* is the error is reproducible?
* if reproducible, do you see the error in safe mode (atom --safe)?

**Comment by Manish-rai21bit** [comment] 2017-08-15 05:35
Hi Rsese,

I get this error each time I open a big csv on atom. The file that I was opening was a csv with the size of 63 MB.
And I get this error even in the safe mode.

**Comment by Ben3eeE** [comment] 2017-08-15 15:26
@Manish-rai21bit Can you share the csv file where you see this issue?

/cc: @maxbrunsfeld

**Comment by lee-dohm** [comment] 2017-08-22 20:06
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/15325. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by lee-dohm** 2017-08-22 20:06 UTC
Labels: more-information-needed, needs-reproduction, regression, uncaught-exception
