### ISSUE TITLE
Tree and gutter not updating after commit

### ISSUE THREAD

**Issue by nvanrees** [atom/git-diff#104] opened 2016-07-04 09:04 UTC
After a commit. The diff colors remain in the gutter and tree.
Only updates after closing and reopening the file, or restarting Atom. Also happens in safe-mode.

Atom version 1.8.0
Git-diff 1.0.1
On Linux Mint 17.3 Cinnamon 64-bit

**Comment by merlijnbruijnes** [comment] 2016-07-13 07:52
Any news about this issue? I have exactly the same problem.

**Comment by 50Wliu** [comment] 2016-07-15 10:56
I believe this is a duplicate of atom/atom#11358 and has been fixed.

**Closed by 50Wliu** 2016-07-15 10:56 UTC
