### ISSUE TITLE
Excluded files still show as ignored in file tree

### ISSUE THREAD

**Issue by download13** [atom/git-diff#100] opened 2016-05-05 20:29 UTC
My `.gitignore` file includes the following lines:

```
dist/server/
!dist/server/Dockerfile
```

Everything in `dist/server/` is now shown as grayed out in the file tree as though it is untracked. Including `dist/server/Dockerfile`, which should be tracked as the gitignore file explicitly excludes it from being ignored.

![File tree](http://i.imgur.com/YskRxbp.png)

**Comment by takhs91** [comment] 2017-01-14 11:49
I experience the same issue. It is also annoying because they are also excluded from the linter plugin

**Comment by maxbrunsfeld** [comment] 2018-09-07 17:17
I think this is a duplicate of https://github.com/atom/tree-view/issues/196

**Closed by maxbrunsfeld** 2018-09-07 17:17 UTC
