### ISSUE TITLE
not work when a parent folder opened

### ISSUE THREAD

**Issue by cszipper** [atom/git-diff#92] opened 2016-03-14 08:34 UTC
I found that if I have a parent folder(which contains the target project)opened before the project, it will not show the colored markers.
for example, if I opened workspace before the project folder, git-diff won't work
workspace/
&nbsp;&nbsp;&nbsp;&nbsp;|- project/
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|- .git/
project/
&nbsp;&nbsp;&nbsp;&nbsp;|- .git/

info: git-diff 0.57.0 Atom 1.5.4

**Comment by arnov** [comment] 2016-05-01 20:17
Yeah, this is pretty annoying, since I work on a lot of different repositories I normally have the parent folder opened.

**Comment by xenithorb** [comment] 2016-08-27 17:25
I can confirm this on the latest RPM on Fedora 24.

It seems Atom / this package 's workflow assume that a "project" is a single repo. 

My logical organizing of a project doesn't work that way, since my "project" is the folder that contains the set of repos for the project. (Or even one more removed from that)

It starts working again if I add the folders separately as projects. (which I don't think I should do - I have an ansible project with 20+ discrete git repos)

**Comment by 50Wliu** [comment] 2016-08-27 17:33
This is a duplicate of atom/atom#2203 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-08-27 17:33 UTC
